Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -46,7 +46,7 @@ fi
 
 # Step 8: Start tmux session and run restart_node.sh
 echo "Starting tmux session and running restart_node.sh..."
-tmux new -d -s node 'cd /ceremonyclient/node/.config && ./restart_node.sh' || { echo "Failed to start tmux session or run restart_node.sh! Exiting..."; exit 1; }
+tmux new -d -s node 'cd /ceremonyclient/node/ && ./restart_node.sh' || { echo "Failed to start tmux session or run restart_node.sh! Exiting..."; exit 1; }
 
 # Step 9: Unzip the file after a 20-second delay
 echo "Unzipping the file after a 20-second delay..."
