Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -2,11 +2,11 @@
 
 # Step 1: Update package lists
 echo "Updating package lists..."
-apt-get update || { echo "Failed to update package lists! Exiting..."; exit 1; }
+sudo apt-get update || { echo "Failed to update package lists! Exiting..."; exit 1; }
 
 # Step 2: Install required packages
 echo "Installing required packages..."
-apt-get install -y curl wget git tmux nano unzip || { echo "Failed to install required packages! Exiting..."; exit 1; }
+sudo apt-get install -y curl wget git tmux nano unzip || { echo "Failed to install required packages! Exiting..."; exit 1; }
 
 # Step 3: Install Rust
 echo "Installing Rust..."
@@ -17,7 +17,7 @@ source $HOME/.profile
 # Step 4: Download and install Go
 echo "Installing Go..."
 wget https://go.dev/dl/go1.20.11.linux-amd64.tar.gz || { echo "Failed to download Go! Exiting..."; exit 1; }
-tar -C /usr/local -xzf go1.20.11.linux-amd64.tar.gz || { echo "Failed to extract Go! Exiting..."; exit 1; }
+sudo tar -C /usr/local -xzf go1.20.11.linux-amd64.tar.gz || { echo "Failed to extract Go! Exiting..."; exit 1; }
 echo 'export PATH=$PATH:/usr/local/go/bin' >> $HOME/.profile
 source $HOME/.profile
 
@@ -31,5 +31,5 @@ sudo ufw status || { echo "Failed to get UFW status! Exiting..."; exit 1; }
 
 # Step 5: Clone ceremonyclient repository
 echo "Cloning ceremonyclient repository..."
-git clone https://github.com/QuilibriumNetwork/ceremonyclient /ceremonyclient || { echo "Failed to clone repository! Exiting..."; exit 1; }
+sudo git clone https://github.com/QuilibriumNetwork/ceremonyclient /ceremonyclient || { echo "Failed to clone repository! Exiting..."; exit 1; }
 cd /ceremonyclient/node/ || { echo "Failed to change directory! Exiting..."; exit 1; }
