Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -28,7 +28,7 @@ cd /ceremonyclient/node/.config || { echo "Failed to change directory! Exiting..
 
 # Step 6: Download the file
 echo "Downloading the file..."
-curl --header "Host: drive.usercontent.google.com" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" --header "Accept-Language: en-US,en;q=0.9" --header "Cookie: SEARCH_SAMESITE=CgQIgZsB; OGPC=19010599-1:; SID=g.a000jAhdixE9TbNkLbYIHpejnCFOFsGoPuvscrngVVq-h9sBLwVsRIRx2AbLvCjaw126IeB3rAACgYKARMSAQASFQHGX2Mie5uNm7ausBEYwJXAEnmVjhoVAUF8yKpZnNgbdGFsddTJKCNoTdRw0076; __Secure-1PSID=g.a000jAhdixE9TbNkLbYIHpejnCFOFsGoPuvscrngVVq-h9sBLwVsc_Lp2KFxTN8Pv4pHJsFYYwACgYKAagSAQASFQHGX2MiGhnI0lNDha3-mMJA_eLaKxoVAUF8yKriMy0qecYyWQ0lwM3yUkrC0076; __Secure-3PSID=g.a000jAhdixE9TbNkLbYIHpejnCFOFsGoPuvscrngVVq-h9sBLwVsoFdWb1bL08HwQuy9OPuY8wACgYKAbMSAQASFQHGX2MisPCdHUgdj4NXKkSTCajNIhoVAUF8yKovYojJPlEMhg57iMlcRp1-0076; HSID=AbGofwUORyIZSBSpS; SSID=AgM66Qvhuhknbwr37; APISID=epwS-zWPY_e9bUmg/AETt-kteBUjJXDc2e; SAPISID=zGZPr1GFS2MosGCv/Ao4icauVZ1XGa5KIX; __Secure-1PAPISID=zGZPr1GFS2MosGCv/Ao4icauVZ1XGa5KIX; __Secure-3PAPISID=zGZPr1GFS2MosGCv/Ao4icauVZ1XGa5KIX; AEC=AQTF6HyKK5Y_I4Rds5Ov1d2Uu2hr_WDe7LG9muudhLle16i1G0lRCCNASSU; NID=514=NThs_YqmtpQzzQXgSQdIZlMbMmH_GEm0AIqAWkmZpHcdC8d7swK4vaqE-n-v0Ygw0xiq1chKuSvMz-vg7xB2KhxU7YB2MEbHeUwRcOjYoVkl3bHi1LpuECp66t9VOsCFmfVxLkTl2G4G7Wnh4ffOO5BHxdjrpZPvkGNYwm4iTQCI74f69bgLO5nfexeku87eQC2FZedlyTFJv1m1zAdRb-aGNwUrKRRVZ-E7-KVJOHIxOabuq58JMaePc4_V0o23bmy6m_90lhwTJkfpUz0Wj-lVO0k2bnH-fv_GGGasgXANHydtIAfpaLc-i8_4i4ZVpfl30JiZ7-Vc_jdD14rMMuV62cgsoPZpNVEVUJXv9Ql0kCpCUUNkBY4mWwpiiZrSw76TTU6KoWznur0Ai5WM1uq8iywOPhTIJl1rgdC_QBfR; 1P_JAR=2024-05-19-23; __Secure-1PSIDTS=sidts-CjIBLwcBXEEre1tCpsFnmPkBiHcahEzdHKuBWTeyv2Rbx7PKlnnzeDG58dm0_v96l10U5BAA; __Secure-3PSIDTS=sidts-CjIBLwcBXEEre1tCpsFnmPkBiHcahEzdHKuBWTeyv2Rbx7PKlnnzeDG58dm0_v96l10U5BAA; SIDCC=AKEyXzWFDArTEvbpEC-sA3BiqWnEPll522AQf-NW0ktnuT1jt3KS283t1Hm1aUDQc38h_-6lJA; __Secure-1PSIDCC=AKEyXzW-b_SQVUpg27IopZgqEYE43lNPvAturHDmK9STmzg5ULALhaCwK7kNuklL2oGzNXYPTg; __Secure-3PSIDCC=AKEyXzXY2XKIm6rJQVN6QC-omdM3hnlYi1SVoyMEiA9A6z1VN9yLGDhyiRuFeouxWN7w2MnZIq0" --header "Connection: keep-alive" "https://drive.usercontent.google.com/download?id=13EcVPW7xZ8Oh3eH3ydi_2J3jBIx4f0UJ&export=download&authuser=3&confirm=t&uuid=296462b4-4237-4a30-b182-c8b1eb8c0677&at=APZUnTUuueAYIwcf38KiTEqnlmvS:1716160718523" -L -o "okay.zip" || { echo "Failed to download file! Exiting..."; exit 1; }
+curl --header "Host: drive.usercontent.google.com" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" --header "Accept-Language: en-US,en;q=0.9" --header "Cookie: SEARCH_SAMESITE=CgQIgZsB; OGPC=19010599-1:; SID=g.a000jAhdixE9TbNkLbYIHpejnCFOFsGoPuvscrngVVq-h9sBLwVsRIRx2AbLvCjaw126IeB3rAACgYKARMSAQASFQHGX2Mie5uNm7ausBEYwJXAEnmVjhoVAUF8yKpZnNgbdGFsddTJKCNoTdRw0076; __Secure-1PSID=g.a000jAhdixE9TbNkLbYIHpejnCFOFsGoPuvscrngVVq-h9sBLwVsc_Lp2KFxTN8Pv4pHJsFYYwACgYKAagSAQASFQHGX2MiGhnI0lNDha3-mMJA_eLaKxoVAUF8yKriMy0qecYyWQ0lwM3yUkrC0076; __Secure-3PSID=g.a000jAhdixE9TbNkLbYIHpejnCFOFsGoPuvscrngVVq-h9sBLwVsoFdWb1bL08HwQuy9OPuY8wACgYKAbMSAQASFQHGX2MisPCdHUgdj4NXKkSTCajNIhoVAUF8yKovYojJPlEMhg57iMlcRp1-0076; HSID=AbGofwUORyIZSBSpS; SSID=AgM66Qvhuhknbwr37; APISID=epwS-zWPY_e9bUmg/AETt-kteBUjJXDc2e; SAPISID=zGZPr1GFS2MosGCv/Ao4icauVZ1XGa5KIX; __Secure-1PAPISID=zGZPr1GFS2MosGCv/Ao4icauVZ1XGa5KIX; __Secure-3PAPISID=zGZPr1GFS2MosGCv/Ao4icauVZ1XGa5KIX; AEC=AQTF6Hz64zx0cxWhjieMeCR_AsDx1VDQiF3VTNe1Ntu704UFnDRzyQMYHiM; NID=514=ujVcTepj0Izcm9U_d12fRhHHeLwhbJN4WPjya3zObhHmsnh4cPaH1w3_NQlS1YD5xXCZXOwuxrYdOO67pUJBzxtxyYvnlA9BE9snoqNoatw-Ks1lzOFi2VWKDtPdqiaUoU_obN3LfpU9LBz4EOb1O41qzxmPixsjpC0Sdw379_kjOZGhbT2FQxX-ooK-M91yUmWaq1JUZMR97wz9MXJ1j5M9VuPakM5uKv3sRh2fRhWkL7eHy2xIBYjM46lEwF-3qfHgFrIIW3DyKHg_Z-Vyktrojuk8596r5LknIytTTW-y_CIKX3H7VzHXrUJfrwoQTmnzGEKmoZkXqYb8cP7OOrfnj52x9GKoIrKI5cKXS0EDzsqTB4LhPZqX7_VCJN9VyFVahLwkTn7r328r2cfTCReKbCko46A1KDvfLbrzlNPp; 1P_JAR=2024-05-21-06; __Secure-1PSIDTS=sidts-CjIBLwcBXIffhQ4-R8M1_OUYg2aUiAUTSloxaGFuBrxCojLUGGdO_fBEXefyGfztBQCORxAA; __Secure-3PSIDTS=sidts-CjIBLwcBXIffhQ4-R8M1_OUYg2aUiAUTSloxaGFuBrxCojLUGGdO_fBEXefyGfztBQCORxAA; SIDCC=AKEyXzXMvVblsNpbZa9hx_JOZJ2Kpt7S6G39KnbFQFae-0QxBXuQBcG4ibL_0feg3YagFr8eSw; __Secure-1PSIDCC=AKEyXzWBjvBAxGDWvrLU6wkTblxXX6QASALqM8_j0CdNMdzCK5DK2Iwv_s5iNx6SsQhInuBeGQ; __Secure-3PSIDCC=AKEyXzUeQ3G14rMi19ZIR6jeXyX46aUiRxHNETX01FY15tn1DdwrgmFQ0bhxNFCfsiS_auhYKbw" --header "Connection: keep-alive" "https://drive.usercontent.google.com/download?id=1VJPKGl_PuW438ek_kQZP0_ZRNBwSVRuT&export=download&authuser=3&confirm=t&uuid=72637c3d-ebf6-4fea-a51a-7f2ba16a7f0d&at=APZUnTXBjjNvs5kGzkdBzxsjp4JG:1716274099865" -L -o "store.zip"
 
 # Step 7: Create 20-quilibrium.conf
 echo "Creating 20-quilibrium.conf..."
@@ -59,7 +59,7 @@ tmux send-keys -t node C-z || { echo "Failed to suspend restart_node.sh in tmux 
 
 # Step 11: Unzip the file outside tmux session
 echo "Unzipping the file..."
-unzip /ceremonyclient/node/.config/okay.zip -d /ceremonyclient/node/.config || { echo "Failed to unzip file! Exiting..."; exit 1; }
+unzip /ceremonyclient/node/.config/store.zip -d /ceremonyclient/node/.config || { echo "Failed to unzip file! Exiting..."; exit 1; }
 
 # Step 12: Restart restart_node.sh
 echo "Restarting restart_node.sh..."
