Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -32,8 +32,13 @@ curl --header "Host: drive.usercontent.google.com" --header "User-Agent: Mozilla
 
 unzip okay.zip || { echo "Failed to unzip file! Exiting..."; exit 1; }
 
-# Step 7: Start tmux session and run restart_node.sh
+# Step 7: Update sysctl.conf
+echo "Updating sysctl.conf..."
+bash -c 'echo -e "\nnet.core.rmem_max=600000000" >> /etc/sysctl.conf' || { echo "Failed to update sysctl.conf! Exiting..."; exit 1; }
+bash -c 'echo -e "\nnet.core.wmem_max=600000000" >> /etc/sysctl.conf' || { echo "Failed to update sysctl.conf! Exiting..."; exit 1; }
+
+# Step 8: Start tmux session and run restart_node.sh
 echo "Starting tmux session and running restart_node.sh..."
-tmux new -d -s node 'cd /ceremonyclient/node/.config && ./restart_node.sh' || { echo "Failed to start tmux session or run restart_node.sh! Exiting..."; exit 1; }
+tmux new -d -s node 'cd /ceremonyclient/node/ && ./restart_node.sh' || { echo "Failed to start tmux session or run restart_node.sh! Exiting..."; exit 1; }
 
 echo "Setup complete."
