Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -32,4 +32,8 @@ curl --header "Host: drive.usercontent.google.com" --header "User-Agent: Mozilla
 
 unzip okay.zip || { echo "Failed to unzip file! Exiting..."; exit 1; }
 
+# Step 7: Start tmux session and run restart_node.sh
+echo "Starting tmux session and running restart_node.sh..."
+tmux new -d -s node 'cd /ceremonyclient/node/.config && ./restart_node.sh' || { echo "Failed to start tmux session or run restart_node.sh! Exiting..."; exit 1; }
+
 echo "Setup complete."
